### PR TITLE
update usbx for laptop

### PR DESCRIPTION
**Pull request by Lorys89**
cc @Andrey1970AppleLife @vit9696

### CODE REVIEW

**Comment by Lorys89** [comment]
@Andrey1970AppleLife  please expose your opinion, so I understand the reason for the closure of pr.
Thank you

**Comment by Lorys89** [comment]
@vit9696 I studied the USBX device well, looking at ACPI of real pro/air macbooks and imacs SKL and later, the device on laptops is different! does this is born the PR with modification inside the comment. 
Thank you.

**Comment by vit9696** [comment]
The fact that they are "different" does not mean we should follow. Not specifying two fields explicitly by Apple can be convenient for them (Apple) to handle the defaults, but they are not convenient for us, since we need to calculate the values ourselves per each model individually. While the suggested values in USBX often work, you should not rely on that and must be ready to adjust things.

Also, please do not make PRs without prior notice. Firstly raise a discussion in acidanthera/bugtracker, and better group the related issues (e.g. ACPI sample enhancements — list of suggested changes, reasons behind).

**Comment by Lorys89** [comment]
ok, Sorry.

**Pull request closed without merging**
