### PR TITLE
Update ShellCheck CI

### PR DESCRIPTION
**Pull request by dakanji**
Updates #48

### CODE REVIEW

**Comment by vit9696** [comment]
I do not think it is a good idea to pollute the source code of the shell script rather than fix it. In my opinion, either exclude the file from checking or fix the issues.

Rodion (@roddy20) could make sure that the script remains functional.

**Comment by dakanji** [comment]
I don't think comments count as pollution but it's your call.

Script was not included before so the PR can just be closed and the matter will be solved if that is the preference.

**Comment by vit9696** [comment]
I agree that this PR is an enhancement, and I thought you would like to drive shellcheck incorporation in Acidanthera anyway, so all the scripts would be changed sooner or later anyway. Not sure what you mean.

**Comment by dakanji** [comment]
Trying to the best of my knowledge to contribute in a small way and don't want to break anything ... especially with this one as it doesn't have a test to verify if I change according to the suggestions.

That's why I thought it best to flag where there are issues that I can't resolve right now so that I can either get back to them later or someone more knowledgeable can pick them up.

I am only able to handle problems in discrete chunks which is why I thought it was a reasonable incremental step of adding informative comments.

I understand that projects have all sorts of considerations to ponder but If you are willing to accommodate a step by step process, then the added comments would ultimately be dealt with.

Pollution is a bit of  strong word and it was in that context that made me think deleting the PR was a possible way forward as the files in question were not touched before.

**Comment by vit9696** [comment]
Ok, this sounds fine to me as long as it is a temporary measure. I guess handling these changes in a separate PR will indeed be better as first we need to have the tool working and then we could address its issues.

**Comment by dakanji** [comment]
BTW. Left the shebang alone as "sh" but there are two non POSIX compliant items

1. Use of local variable on Line 52: `local key`
2. Use of expansion on 77: `Boot008{1..3}`

Not sure how the script actually worked/works.

Personally I think shebang should change to bash.

Regarding comments elsewhere on not being able to rely on bash, i think that is a bit of a leap as while Apple has indeed changed the DEFAULT shell to zsh, as long as bash is not actually REMOVED, and there is no indication this is imminent, any script with a bash shebang would be interpreted accordingly. 

Same way you could/can run zsh scripts when bash was/is the default as long as you indicated this in the shebang ... Since OS X Tiger when zsh was added (IIRC).

Anyway, that's an item for the project team to decide on but should be done in full disclosure.

**Comment by vit9696** [comment]
In my opinion, we should expect Apple to remove bash in the nearest future as it is GPL and end of life. The use of `local` keyword and expansion could be easily fixed I believe.

**Pull request merged**
