### PR TITLE
for HP Z620 dual cpus socket

### PR DESCRIPTION
**Pull request by ZISQO**
.

### CODE REVIEW

**Comment by vit9696** [comment]
That's Sandy Bridge, Sandy Bridge does not support XCPM. Adding plugin-type to one socket is also enough.

**Comment by ZISQO** [comment]
> That's Sandy Bridge, Sandy Bridge does not support XCPM. Adding plugin-type to one socket is also enough.

also it's possible to do with legacy AICPUPM pathed file of.
already i was successed with Z420, 620 for Catalina 10.15.x and Sleep and wake up perfectly.

**Comment by usr-sse2** [comment]
> That's Sandy Bridge, Sandy Bridge does not support XCPM. Adding plugin-type to one socket is also enough.
Plugin-type=1 is not only for XCPM. Ivy Bridge doesn't support XCPM, but requires plugin-type 1 so it loads X86PlatformPlugin.

**Comment by vit9696** [comment]
Why do you load X86PlatformPlugin on Sandy Bridge, when it is supposed to use ACPI_SMC_PlatformPlugin?

**Comment by BrushXue** [comment]
> > That's Sandy Bridge, Sandy Bridge does not support XCPM. Adding plugin-type to one socket is also enough.
> 
> also it's possible to do with legacy AICPUPM pathed file of.
> already i was successed with Z420, 620 for Catalina 10.15.x and Sleep and wake up perfectly OC opencore. so could you please say to quickly?

Could please share your EFI folder? I have dual E5 and want to switch to OC but didn't find any tutorial for X79 or C602.

**Pull request closed without merging**
