### PR TITLE
Build: Fix ShellCheck warning in macbuild

### PR DESCRIPTION
**Pull request by dakanji**
Fix for final outstanding warning. Passes ShellCheck.
Tested and builds without error locally ... Should pass TravisCI

### CODE REVIEW

**Comment by vit9696** [comment]
Hmm, are you sure it is POSIX compliant? Well, we do not care about POSIX, but at least whether it works everywhere.

**Comment by dakanji** [comment]
Seems to be. Changing shebang to `#!/bin/sh` results in 11 POSIX related warnings in ShellCheck from zero with `#!/bin/bash` ... this is not one of them.

POSIX_ERRS

**Comment by vit9696** [comment]
Well, did you you actually check the standard or at least ran with different shells? Or is that blind relying on the instrument?

**Comment by dakanji** [comment]
I did not check the standards and do blindly rely on it here.

In any case... 
- The file is clearly not POSIX compliant as you say
- The item clearly builds cleanly 
- Shebang is present and any interpreter would use this ... what exactly needs to be checked again?

**Pull request merged**
