### PR TITLE
OcLog: Update filtering

### PR DESCRIPTION
**Pull request by mikebeaton**
- Filter log strings after formatting
   - Strings which are only valid log lines after formatting do occur, and were not getting filtered because of this
 - Never filter WARN and ERROR log lines
   - I was getting quite confused by missing a key DEBUG_WARN message, then realised it was filters
   - I do realise there are cons as well as pros to this suggested change (mainly, you could not stop yourself getting spammed by WARN messages from a given module using the filter - if that issue were to happen, and if this change was applied; but on balance I found lower surprisal from not filtering these) 
 - Fix positive filtering
   - I would say it was doing nothing, at state of code at which this PR is applied - not sure if this is a regression?
 - Fix minor issue in valid log prefix algorithm
   - Was previously not checking the zeroth character for validity, according to its own rules

### CODE REVIEW

**Review by vit9696 — APPROVED** [review]
Looks good to me.

**Comment by mikebeaton** [comment]
Hi @vit9696 - thank you for feedback, I just remembered one other possible change to make here at the same time. This is my log for HDA entries, after this fix:

```
00:000 00:000 HDA: GPIO setup stages 0x0 GPIO pin mask 0x0 (auto) Restore NSNPEN 0 Force device PciRoot(0x0)/Pci(0x1f,0x3) Setup delay 0
00:034 00:034  BlockSize : 512 
00:037 00:003  LastBlock : 1D160FFF 
00:042 00:004 PartitionValidMbr: Bad MBR partition size EndingLBA(E9E9E9E7) > LastLBA(1D160FFF)
00:058 00:016  BlockSize : 512 
00:064 00:005  LastBlock : 14F46FD7 
00:080 00:015  BlockSize : 512 
00:083 00:003  LastBlock : 53AF947 
00:099 00:015  BlockSize : 512 
00:102 00:003  LastBlock : 3FFFF 
00:115 00:013  BlockSize : 512 
00:119 00:003  LastBlock : AF53FFF 
00:124 00:005 PartitionValidMbr: Bad MBR partition size EndingLBA(DEB56E8B) > LastLBA(AF53FFF)
00:132 00:007  BlockSize : 512 
00:135 00:003  LastBlock : 12B7FF 
00:141 00:006 PartitionValidMbr: Bad MBR partition size EndingLBA(DEB56E8B) > LastLBA(12B7FF)
00:149 00:008  BlockSize : 512 
00:153 00:003  LastBlock : 3AF8FFF 
00:162 00:009  BlockSize : 512 
00:166 00:003  LastBlock : CBDF7FF 
00:172 00:005 PartitionValidMbr: Bad MBR partition size EndingLBA(DEB56E8B) > LastLBA(CBDF7FF)
00:186 00:014 HDA: Connecting controller - PciRoot(0x0)/Pci(0x1F,0x3)
00:190 00:003 HDA: Controller disable no snoop
00:193 00:003 HDA: Controller version 1.0
00:196 00:003 HDA: Capabilities:
00:199 00:003 HDA:  | 64-bit: Yes  Serial Data Out Signals: 0
00:203 00:003 HDA:  | Bidir streams: 0  Input streams: 7  Output streams: 9
00:206 00:003 HDA: Controller is Intel 300 Series HD Audio Controller
00:309 00:103 HDA: Controller protocols installed
00:337 00:028 HDA: Controller initialized
00:341 00:004 HDA: Connecting codec 0x0
00:350 00:008 HDA:  | Codec ID: 0x10EC:0x255
00:359 00:008 HDA:  | Codec name: Realtek ALC255
00:368 00:008 HDA:  | Codec contains 1 function groups, start @ 0x1, end @ 0x1
00:377 00:008 HDA:  | Function group @ 0x1 is of type 0x1
00:406 00:029 HDA:  | Function group @ 0x1 output amp capabilities: 0x0
00:420 00:013 HDA:  | Function group @ 0x1 GPIO capabilities: 0x40000003
00:429 00:008 HDA:  | Function group @ 0x1 contains 34 widgets, start @ 0x2, end @ 0x23
00:462 00:032 HDA:  | Widget @ 0x2 output amp capabilities: 0x25757
00:526 00:064 HDA:  | Widget @ 0x3 output amp capabilities: 0x25757
01:107 00:580 HDA:  | Widget @ 0x14 output amp capabilities: 0x80000000
01:191 00:084 HDA:  | Widget @ 0x17 output amp capabilities: 0x80000000
01:456 00:265 HDA:  | Widget @ 0x1B output amp capabilities: 0x80000000
01:641 00:184 HDA:  | Widget @ 0x21 output amp capabilities: 0x80000000
01:881 00:239 HDA:  |  Widget @ 0xC (type 0x2)
01:892 00:011 HDA:  |  Widget @ 0x2 (type 0x0)
01:896 00:003 HDA:  | Port widget @ 0x14 is an output (pin defaults 0x90170150) (bitmask 1)
01:915 00:018 HDA:  |  Widget @ 0xC (type 0x2)
01:919 00:003 HDA:  |  Widget @ 0x2 (type 0x0)
01:923 00:003 HDA:  | Port widget @ 0x1B is an output (pin defaults 0x2011020) (bitmask 2)
01:937 00:013 HDA:  |  Widget @ 0xC (type 0x2)
01:940 00:003 HDA:  |  Widget @ 0x2 (type 0x0)
01:944 00:003 HDA:  | Port widget @ 0x21 is an output (pin defaults 0x221105F) (bitmask 4)
01:966 00:021 HDA: Codec protocols installed
01:970 00:003 HDA: Codec initialized
01:974 00:004 HDA: Connecting codec 0x2
01:986 00:011 HDA:  | Codec ID: 0x8086:0x280B
01:995 00:009 HDA:  | Codec name: Intel Kaby Lake HDMI
02:008 00:012 HDA:  | Codec contains 1 function groups, start @ 0x1, end @ 0x1
02:017 00:008 HDA:  | Function group @ 0x1 is of type 0x1
02:046 00:028 HDA:  | Function group @ 0x1 output amp capabilities: 0x0
02:060 00:014 HDA:  | Function group @ 0x1 GPIO capabilities: 0x0
02:072 00:012 HDA:  | Function group @ 0x1 contains 2 widgets, start @ 0x2, end @ 0x3
02:167 00:094 HDA:  | Widget @ 0x3 output amp capabilities: 0x80000000
02:201 00:034 HDA:  |  Widget @ 0x2 (type 0x0)
02:207 00:006 HDA:  | Port widget @ 0x3 is an output (pin defaults 0x18560010) (bitmask 1)
02:216 00:008 HDA: Codec protocols installed
02:220 00:004 HDA: Codec initialized
02:302 00:081  BlockSize : 512 
02:306 00:003  LastBlock : 14F46FD7 
02:632 00:326  BlockSize : 512 
02:636 00:003  LastBlock : 53AF947 
```

So, the question is, what should be done with 'unknown' entries (which are not at WARN or ERROR), in the case of positive (only show certain entries) filtering - as above?

Currently, unknown entries are shown in both positive and negative (remove certain entries) filtering. But based on the above, it might be a good idea to also filter out unknown entries, when we are doing positive filtering?

**Comment by vit9696** [comment]
I think make a separate change for that. Most likely we will want a separate tag for unknown entries, perhaps a special symbol (e.g. `?`) or something.

**Comment by mikebeaton** [comment]
@PMheart - I hope it's okay if I merge this for now and wait for you to ping me if you spot anything that would need changing.

**Comment by PMheart** [comment]
Yes, looks good to me too. Thanks!

**Pull request merged**
