### PR TITLE
SSDT-PNLF Fix code for CFL + (whiskey lake fix) 

### PR DESCRIPTION
**Pull request by Lorys89**
in the previous version it only had problem with some laptops with whiskey lake cpu, but it worked on cfl and cml and icl, with new modification solved the problem.

### CODE REVIEW

**Comment by vit9696** [comment]
Please explain why deleting the code is legit here.

**Comment by Lorys89** [comment]
> Please explain why deleting the code is legit here.

that code I deleted on cfl+ is not essential, keeping that code works on cfl, cml and icl but on whiskey lake creates problems since it makes it load uid 10 and not 13

**Comment by Lorys89** [comment]
but I repeat it is a problem only with whiskey lake generation, the others work well with current pnlf release. 
this new version continues to work well even with the aforementioned ones.

**Comment by stevezhengshiqi** [comment]
Reported by my mates that some CML machines can not change brightness in 3 minutes. After 3 minutes, everything else works well. No log for now. Occured since updated SSDT-PNLF in https://github.com/acidanthera/OpenCorePkg/commit/cbea3f1be8e5a22ad303c71a558332ad3c9d9ead

**Comment by Vorshim92** [comment]
> Reported by my mates that some CML machines can not change brightness in 3 minutes. After 3 minutes, everything works well. No log for now. Occured since updated SSDT-PNLF in https://github.com/acidanthera/OpenCorePkg/commit/cbea3f1be8e5a22ad303c71a558332ad3c9d9ead

I have a i7 10510u cml and it works perfectly. Also with the first version.. Never had this problem so maybe it comes from other stuff in your efi?

**Comment by Vorshim92** [comment]
> Reported by my mates that some CML machines can not change brightness in 3 minutes. After 3 minutes, everything works well. No log for now. Occured since updated SSDT-PNLF in https://github.com/acidanthera/OpenCorePkg/commit/cbea3f1be8e5a22ad303c71a558332ad3c9d9ead

Probably is this: 
-igfxblr boot argument (and enable-backlight-registers-fix property) to fix backlight registers on CFL + platforms.

Just add to their efi this Bootarg in nvram "-igfxblr" or in the Dev prop patch "enable-backlight-registers-fix" with 01000000 DATA

**Comment by stevezhengshiqi** [comment]
@Vorshim92 Thanks for the reply. I am still confused about CFL part in SSDT-PNLF. Why we need to assign COFFEELAKE_PWMMAX to PWMMAX in SSDT-PNLF while in SSDT-PNLFCFL, we only need to change UID to 13? To me, SSDT-PNLFCFL is a much cleaner and native way to inject UID without modifying PWM max value.

**Comment by Lorys89** [comment]
> @Vorshim92 Thanks for the reply. I am still confused about CFL part in SSDT-PNLF. Why we need to assign COFFEELAKE_PWMMAX to CFL pwm in SSDT-PNLF while in SSDT-PNLFCFL, we only need to change UID to 13? To me, SSDT-PNLFCFL is a much cleaner and native way to inject UID without modifying PWM max value.

sorry meddling, but you did not understand how it works you just have to fill in aml, and then he alone according to your device id of the igpu set in automatic correct uid, in your case sect 13 in automatic since you have cfl. 
you don't have to change any value in ssdt, you just have to save it in aml.
and you have to use -igfxblr as bootarg from cfl and later
Kind regards.

**Comment by lorys89-is-as-dumb-as-baio77** [comment]
My modest opinion is that all this mess on SSDT-PNLF could have been avoided with few more lines of documentation at the beginning of the `.dsl`. These PRs https://github.com/acidanthera/OpenCorePkg/pull/279 and https://github.com/acidanthera/OpenCorePkg/pull/284 bloated my mail with unnecessary/wrong modifications which led to nothing else than broken behaviours gently provided by @Lorys89. Please stop using randomly `If (_OSI ("Darwin"))` and stop wasting vit9696's time on this crap. 

Refrence: https://github.com/acidanthera/bugtracker/1747

**Comment by stevezhengshiqi** [comment]
@Lorys89 Thanks for the reply. SSDT-PNLF has detailed notations so it's not difficult to understand how it works on assigning PWM value. What I doubted is the necessity for CFL users transition from SSDT-PNLFCFL to SSDT-PNLF since PNLFCFL seems to be a much decent UID injection targeted for CFL+ users.

-igfxblr is not needed on my friend's machine when he uses SSDT-PNLFCFL. I will ask him to try this with PNLFCFL. BTW, still hoping that AppleBacklightSmoother could be updated as it was also a great solution for brightness adjustion.

**Comment by stevezhengshiqi** [comment]
What I suggest and I believe the behind reason for Rehabman having a separated PNLFCFL is letting CFL machine's LMAX and PWM untouched. In the new version of PNLF, CFL machine's UID is set to 19 and triggers [F19Txxxx](https://github.com/acidanthera/WhateverGreen/blob/1.4.7/WhateverGreen/kern_weg.cpp#L74) backlight data. While UID 13 in SSDT-PNLFCFL will call native AppleBacklight.kext. (For some reason, machine within PNLFCFL's UID is still set to 19?)
I haven't dived too deep on this since I don't have a CFL machine until a week later. But thanks to everyone who worked on the PNLF improvement.

**Comment by Lorys89** [comment]
> What I suggest and I believe the behind reason for Rehabman having a separated PNLFCFL is letting CFL machine's LMAX and PWM untouched. In the new version of PNLF, CFL machine's UID is set to 19 and triggers [F19Txxxx](https://github.com/acidanthera/WhateverGreen/blob/1.4.7/WhateverGreen/kern_weg.cpp#L74) backlight data. While UID 13 in SSDT-PNLFCFL will call native AppleBacklight.kext. (For some reason, machine within PNLFCFL's UID is still set to 19?)
> I haven't dived too deep on this since I don't have a CFL machine until a week later. But thanks to everyone who worked on the PNLF improvement.

then uid 19 (decimal) converted is uid 0x13 (hex)

**Comment by TonyC5** [comment]
Since updating SSDT-PNLF released with OC 0.7.2 and then OC 0.7.3 on my hack, I have experienced kernel panics where logs suggest a graphics issue (com.apple.driver.AppleIntelKBLGraphics).  I have reverted to SSDT-PNLF (the non-CFL version) released prior to OC 0.7.2 (none of the latest CFL changes) and haven't observed the kernel panics, but I'm still testing.  My system details are below.  Before I spend more time trying to diagnose and isolate the cause of the com.apple.driver.AppleIntelKBLGraphics kernel panic, does it make sense that the revised (with CFL) SSDT-PNLF could cause com.apple.driver.AppleIntelKBLGraphics kernel panics?

My system:
- i5-8250u/UHD620 Kabylake R
- SMBIOS: MBP14,1
- Big Sur 11.6
- OC 0.7.3, WEG 1.5.3, Lilu 1.5.6

panic details:
0xffffffac9be23860 : 0xffffff7faa10df53 com.apple.driver.AppleIntelKBLGraphics : __ZN17IGHardwareContext4freeEv + 0x3b
0xffffffac9be23960 : 0xffffff7faa10dcf6 com.apple.driver.AppleIntelKBLGraphics : __ZN17IGHardwareContext15initWithOptionsEP11IGAccelTaskRK23IGHardwareContextParamsh + 0x69a
0xffffffac9be239c0 : 0xffffff7faa10d640 com.apple.driver.AppleIntelKBLGraphics : __ZN17IGHardwareContext11withOptionsEP11IGAccelTaskRK23IGHardwareContextParamsh + 0x42
0xffffffac9be239f0 : 0xffffff7faa0c064f com.apple.driver.AppleIntelKBLGraphics : __ZN19IGAccelCommandQueue29createHardwareContextIfNeededEh + 0x4d
0xffffffac9be23a10 : 0xffffff7faa0c06ba com.apple.driver.AppleIntelKBLGraphics : __ZN19IGAccelCommandQueue11setPriorityE28eIOAccelCommandQueuePriority + 0x44
0xffffffac9be23a40 : 0xffffff7faa9f8fca com.apple.iokit.IOAcceleratorFamily2 : __ZN19IOAccelCommandQueue14updatePriorityEv + 0x64
0xffffffac9be23a60 : 0xffffff7faa9f9326 com.apple.iokit.IOAcceleratorFamily2 : __ZN19IOAccelCommandQueue27set_priority_and_backgroundE28eIOAccelCommandQueuePriorityS0_ + 0xb0
0xffffffac9be23aa0 : 0xffffff801041d67e mach_kernel : __ZN12IOUserClient14externalMethodEjP25IOExternalMethodArgumentsP24IOExternalMethodDispatchP8OSObjectPv + 0x1de
0xffffffac9be23af0 : 0xffffff7faa0c04be com.apple.driver.AppleIntelKBLGraphics : __ZN19IGAccelCommandQueue14externalMethodEjP25IOExternalMethodArgumentsP24IOExternalMethodDispatchP8OSObjectPv + 0x1e

**Comment by TonyC5** [comment]
@1alessandro1 , thank you for the follow-up.  @Lorys89 did not delete my comment.  I deleted my comment (which originally asked if SSDT-PNLF might cause the kernel panic) because the kernel panic still happens with the the non-CFL version of SSDT-PNLF.  I have now reverted to OC 0.7.1 and corresponding kexts released with OC 0.7.1 (WEG, Lilu, etc) in an attempt to isolate the kernel panic.

I apologize for the false alarm - I deleted my comment, because I don't think my kernel panic is caused by SSDT-PNLF.

**Comment by Lorys89** [comment]
> @1alessandro1 , thank you for the follow-up. @Lorys89 did not delete my comment. I deleted my comment (which originally asked if SSDT-PNLF might cause the kernel panic) because the kernel panic still happens with the the non-CFL version of SSDT-PNLF. I have now reverted to OC 0.7.1 and corresponding kexts released with OC 0.7.1 (WEG, Lilu, etc) in an attempt to isolate the kernel panic.
> 
> I apologize for the false alarm - I deleted my comment, because I don't think my kernel panic is caused by SSDT-PNLF.

ssdt pnlf cannot cause kp, or starts or does not start (does not load) investigates sssdt pnlf cannot cause kp, or start or not start (does not load) investigates your problem, it's next time write about acidanthera bugtracker. 
Have a nice day.

**Comment by TonyC5** [comment]
My hack (HP Envy Kabylake R i5-8250U/UHD620) BIOS does not permit configuration of video RAM, so I configured framebuffer-fbmem and framebuffer-stolenmem as I understood from [here](https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/vram.html).  I used the 9MB and 19MB values respectively from the Dortania post-install guide.  After increasing these values (to 21MB and 39MB  respectively), I am no longer observing the Kabylake kernel panic.  I will continue to monitor and report back if anything changes.

**Pull request merged**
