### PR TITLE
Add comment about prev-lang:kbd (#1960)

### PR DESCRIPTION
**Pull request by rkarsnk**
https://github.com/acidanthera/bugtracker/issues/1960

### CODE REVIEW

**Comment by mifjpn** [comment]
I pay tribute to the efforts of the developers.
In Japan, the following sequences are generally used on a daily basis. (Ja-JP: 0 seems to be used by programmers in many cases)
prev-lang:kbd  ja-JP:252
Since it is set like this on an actual Mac, please add this notation as well. 
Sample Web-page
https://tamoc-com.translate.goog/display-nvram/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja&_x_tr_pto=wapp

**Comment by rkarsnk** [comment]
@mifjpn 
This PR includes `ja-JP:KANA`. so I will not add `ja-JP:252` at this PR. 
If you want, create an issue and send a PR.

**Comment by mifjpn** [comment]
Thnak you for quick merge,@rkarsnk and @Andrey1970AppleLife
If ja-JP: KANA includes the functions of ja-JP: 252, there is no problem.
Simply, the actual MAC uses ja-JP: 252.
Although it is a pull request, I made a suggestion.
thank you very much.

**Comment by rkarsnk** [comment]
Thank you for merge and fix.
So, I'll delete my fork repository.

**Comment by mifjpn** [comment]
Thank you very much. Andrey.
I would like to suggest to put in a great manual about the main languages of each country.
Or is it better to leave it to the configuration suite software, which fits the design philosophy?
Please think about it and see what you think.
Thank you very much.

**Pull request merged**
