### PR TITLE
Configuration.tex has toogle instead of toggle (twice)

### PR DESCRIPTION
**Pull request by perez987**

### CODE REVIEW

**Comment by PMheart** [comment]
Hello! Thanks for fixing this. Please rebuild the pdf as well. In case you do not have LaTeX installed, I could help.

**Comment by perez987** [comment]
Good night. I haven't Latex, not even used it. But I like to learn.
You can guide me in the direction of what I should do to compile the PDF or help me in the way you prefer.
Thank you very much!!!

**Comment by PMheart** [comment]
Basically you need to install [MacTeX](https://www.tug.org/mactex/) and then run our `Docs/BuildDocs.tool`, then commit and push. For simplicity I have done it for you and merged this PR. Thank you for your contribution!

**Comment by perez987** [comment]
Thank you so much. Noted for the next time. I will train what I have learned.

**Pull request merged**
