### PR TITLE
CrScreenshotDxe: Work around TPL-related ASSERT within firmware compiled to assert

### PR DESCRIPTION
**Pull request by mikebeaton**
(such as recently updated DEBUG version of OpenDuet)

### CODE REVIEW

**Comment by vit9696** [comment]
cc @NikolajSchlej

**Review by vit9696 — APPROVED** [review]

**Comment by mikebeaton** [comment]
In the context of debug build of Ovmf there is no such issue, so needs further investigation as to why.

**Comment by mikebeaton** [comment]
I can confirm that the same issue arises in current EDK-II OvmfPkg. It seems very hard to compile OvmgPkg with ASSERTs enabled and get anywhere - it hits lots of ASSERTs - but you can single step from where FatPkg tries to acquire its lock, and see exactly the same issue.

**Comment by mikebeaton** [comment]
In case it helps to clarify what I am seeing (when debug prints and asserts are enabled in firmware), this visible assert message is:

```
FATAL ERROR - RaiseTpl with OldTpl(0x10) > NewTpl(0x8)
ASSERT [DxeCore] Tpl.c(66): ((BOOLEAN)(0==1))
```

and the call stack after tripping this is:

Screenshot 2024-04-28 at 10 55 24

**Comment by mikebeaton** [comment]
FWIW Issue is confirmed present with OC 0.8.7 and DEBUG OVMF, so is not caused by any recent updates, just showing up because we recently updated OpenDuet DEBUG version to assert - and [fixed all the other asserts](https://github.com/acidanthera/bugtracker/issues/2397) we have found so far.

**Review by vit9696 — APPROVED** [review]
Please make a PR in https://github.com/LongSoft/CrScreenshotDxe as well. We need to backport it there.

**Pull request merged**
