### PR TITLE
Debug: Add support for 32-bit on 32-bit under GDB

### PR DESCRIPTION
**Pull request by mikebeaton**
In addition to existing support for 32-bit on 64-bit

### CODE REVIEW

**Comment by mikebeaton** [comment]
Apologies - directory names need updating for change from `Ia32` to `IA32` (and will prevent it working on case sensitive FS like Unix until changed) - will do this eve.

**Comment by mikebeaton** [comment]
Sorry, running commentary, but I've switched back to `Ia32` as the canonical name (but allowing `IA32` now, e.g. same as target arch spec for EDK and OC build scripts).

**Comment by mikebeaton** [comment]
Checked working in Linux (gdb 32/32, gdb 32/64, lldb 64/64) and macOS (gdb 32/32, gdb 32/64, lldb 64/64).

**Comment by vit9696** [comment]
Looks good to me, merged, tyvm!

**Pull request merged**
