### PR TITLE
Update firmware data

### PR DESCRIPTION
**Pull request by wy414012**

### CODE REVIEW

**Comment by PMheart** [comment]
@Andrey1970AppleLife Hi Andrey! Could you please review this? Thanks!

**Comment by Andrey1970AppleLife** [comment]
> @Andrey1970AppleLife Hi Andrey! Could you please review this? Thanks!

I can fix and merge it, but usually I don't update on a firmware from beta macOS.

**Comment by Andrey1970AppleLife** [comment]
Oh, OEMStrings is edited manually, but OEMStrings is necessary to copy entirely. And I doubt that the utility for unpacking was used.
Closed

**Comment by wy414012** [comment]
@Andrey1970AppleLife  Thanks for pointing out the inadequacies, I can use `strings ./*.fd | grep -A 10 "** ROM Version"` to match the printout directly to the yam file, as I found some firmwares have UUIDs and some don't. I don't know if direct output replacement will cause an exception.

**Pull request closed without merging**
