### PR TITLE
SerializeLib: rename `plist metadata` to `plist multidata` in library code and docs

### PR DESCRIPTION
**Pull request by Bmju**
https://github.com/acidanthera/bugtracker/issues/1501

### CODE REVIEW

**Comment by dakanji** [comment]
NB: These changes have been incorporated in #213 to avoid potential rebase conflicts.

**Comment by Bmju** [comment]
> NB: These changes have been incorporated in #213 to avoid potential rebase conflicts.

Including matching code changes, obv. Cool.

**Comment by vit9696** [comment]
Closing this then.

**Comment by Bmju** [comment]
(PS @dakanji For the record not convinced there'd have been any problem merging these after, yours, actually? But np - onwards!)

**Comment by dakanji** [comment]
Possibly, didn't look in detail and just wanted to avoid potential until the pending item is merged. 
Hope not an issue.

**Pull request closed without merging**
