### PR TITLE
OpenCanopy: Partial audio assist support

### PR DESCRIPTION
**Pull request by usr-sse2**
TODO:
- [x] Announce all boot entries after welcome message and after revealing hidden options
- [-] Maybe announce initially selected option? Need to check how it's done on Mac

### CODE REVIEW

**Comment by erdnaxela02** [comment]
Is there an option to partially enable audio?
In version 0.6.4 the audioassist read the "welcome to opencore" and the boot entry which was launched "loading" "MacOs"
Since update 0.6.5 audioassist has announced all boot entries after welcome message and after revealing hidden options as expected in this post.
I can't find a detailed guide for all of the opencanopy options. So far I have taken OpenCanopy.efi from 0.6.4 with OpenCore.efi 0.6.5 and even if it works I don't think it is optimal?
Thanks for your help

**Comment by Andrey1970AppleLife** [comment]
> Is there an option to partially enable audio?
> In version 0.6.4 the audioassist read the "welcome to opencore" and the boot entry which was launched "loading" "MacOs"
> Since update 0.6.5 audioassist has announced all boot entries after welcome message and after revealing hidden options as expected in this post.
> I can't find a detailed guide for all of the opencanopy options. So far I have taken OpenCanopy.efi from 0.6.4 with OpenCore.efi 0.6.5 and even if it works I don't think it is optimal?
> Thanks for your help

Works correctly. In versions before 0.6.5 audio assistant wasn't implemented completely.
The audio assistant intended for users with limited opportunities of sight.

**Comment by erdnaxela02** [comment]
Okay. I loved it when it didn't work properly ^^
When I booted up my computer, a personalized voice would just say "welcome to openCore. Loading MacOs"
I had the impression that my computer was talking to me :)
and it allowed me to follow the progress of the start-up while I did not have my eyes on the screen ^^
Thanks for your precisions

**Comment by erdnaxela02** [comment]
> > Is there an option to partially enable audio?
> > In version 0.6.4 the audioassist read the "welcome to opencore" and the boot entry which was launched "loading" "MacOs"
> > Since update 0.6.5 audioassist has announced all boot entries after welcome message and after revealing hidden options as expected in this post.
> > I can't find a detailed guide for all of the opencanopy options. So far I have taken OpenCanopy.efi from 0.6.4 with OpenCore.efi 0.6.5 and even if it works I don't think it is optimal?
> > Thanks for your help
> 
> Works correctly. In versions before 0.6.5 OpenCanopy audio assistant wasn't implemented completely.
> Before version 0.6.5 audio assistant completely worked only in the built-in piker.
> The audio assistant intended for users with limited opportunities of sight.

Okay. I loved it when it didn't work properly ^^
When I booted up my computer, a personalized voice would just say "welcome to openCore. Loading MacOs"
I had the impression that my computer was talking to me :)
and it allowed me to follow the progress of the start-up while I did not have my eyes on the screen ^^
Thanks for your precisions

**Pull request merged**
