### PR TITLE
opencore compiled version

### PR DESCRIPTION
**Pull request by kaoskinkae64**
exists or it is possible to create a program or utility to know the compiled realse or beta version that we are using. what we use the betas on a daily basis interesting series to know which one we are using at that moment

### CODE REVIEW

**Comment by dreamwhite** [comment]
> exists or it is possible to create a program or utility to know the compiled realse or beta version that we are using. what we use the betas on a daily basis interesting series to know which one we are using at that moment

As already stated in Configuration.pdf, to obtain the current booted OpenCore version, given a proper `ExposeSensitiveData` bit-mask value, the following command can be used:

`nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version`

Hope this clears your doubts

**Comment by kaoskinkae64** [comment]
> `nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version`

it's not that, i know that build version

6099ed0 | OcAppleKernelLib: Fix Windows builds | DEBUG | RELEASE

**Comment by dreamwhite** [comment]
> > `nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version`
> 
> it's not that, i know that build version
> 
> [6099ed0](https://github.com/acidanthera/OpenCorePkg/commit/6099ed0d2412bea5ba8a856af5a8b7385059f264) | OcAppleKernelLib: Fix Windows builds | DEBUG | RELEASE

Then I misunderstood your question or you haven't explained it better. Also I don't get the reason why you opened a PR that has nothing to do with your issue. Please use bugtracker for this type of question. The title can be something like `[Feature Request] OpenCore version` and possibly ask the devs, if not already done, to add the commit/tag shortened SHA hash.

cc @Andrey1970AppleLife

**Comment by kaoskinkae64** [comment]
> 
thanks for the clarification I don't know very well how to publish but that's how the question is to know the compiled beta version that I'm using type terminal

**Pull request closed without merging**
