### PR TITLE
Support both python 2 and 3

### PR DESCRIPTION
**Pull request by corpnewt**
f-strings are python 3 only.  This commit uses .format() instead which works on both python 2 and 3.  The shebang remains python3 as that's preferred.

### CODE REVIEW

**Comment by vit9696** [comment]
Where do we need Python 2? Transition to Python 3 was intended.

**Comment by corpnewt** [comment]
I had worked with a user recently who was intending to download 10.7 on a machine currently running Vista - which they were unable to install python 3 to.  The changes in this PR don't affect python 3's functionality - but don't exclude python 2 support.

**Comment by vit9696** [comment]
Not sure we want to support this really. The change makes the code less readable. Sorry.

**Comment by corpnewt** [comment]
Not a problem.  Thank you for looking at it.

**Pull request closed without merging**
