### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ZISQO**
add a korean discussion forum

### CODE REVIEW

**Comment by Andrey1970AppleLife** [comment]
The site does not work.
Google tells that this site about: "Hardware software knowledge sharing site for photo image editing."

**Comment by Andrey1970AppleLife** [comment]
@BarbaraPalvin, what you about it tell?

**Comment by vit9696** [comment]
@Andrey1970AppleLife, I have already contacted him in private, and the situation is as follows. In Korea most macOS-related websites require registration to even view the forum pages. This does not make sense to me, so it is best to decline this change.

**Comment by ZISQO** [comment]
already opened that.

**Comment by hbfs** [comment]
@vit9696 the sixflow community is excellent. It helped me immensely for my first hackintosh. I'm not a Korean native speaker, but many users came to my aid. 

The reason its private is many folks in Korea take the hackintosh info and charge people large sums to build a hackintosh, without contributing anything back to the community.

Its fairly easy to join the forums and as long as you contribute back after getting help, its easy to access info. This keeps the quality of content very high.

**Pull request closed without merging**
