### PR TITLE
Remove russian forums

### PR DESCRIPTION
**Pull request by YarosMallorca**
Don't support russia!

### CODE REVIEW

**Comment by 1alessandro1** [comment]
Are you crazy? You need to thank those forums. They are the reason why acidanthera and OpenCore exist.

**Comment by YarosMallorca** [comment]
@1alessandro1 you support russia??? Argressor country???

[Stand With Ukraine](https://stand-with-ukraine.pp.ua)

**Comment by velickovicdj** [comment]
> Don't support russia!

Slavs (mostly Russians) rule the Hackintosh world. You can hate Russia, but please don't be stupid.

**Comment by YarosMallorca** [comment]
I am not stupid, but listing ruzzian forums on here is too much.

**Comment by 1alessandro1** [comment]
> @1alessandro1 you support russia??? Argressor country???
> 
> [Stand With Ukraine](https://stand-with-ukraine.pp.ua)

I don't support any war. Tell me what developers of a bootloader have to do with war. 

You're just spamming with your pull requests.

**Comment by YarosMallorca** [comment]
PLUS, those links are not working, maybe it's my ISP blocking .ru domains but still.

**Comment by vtrxxl** [comment]
> Don't support russia!

no Russia, no opencore 😂

**Comment by YarosMallorca** [comment]
> 
> I don't support any war. Tell me what developers of a bootloader have to do with war.
> 
> You're just spamming with your pull requests.

Sorry for "spamming" but think about this. You're routing traffic to their websites, giving money for them to launch missiles at Ukraine, my home country. Do you consider it normal?

**Comment by 1alessandro1** [comment]
@YarosMallorca this is not the place for this discussion. Please leave war topics outside of this repository and this organisation. They have nothing to do with war and did not decide to invade Ukraine with vote, not through democracy they standed up against your country, so keep your rage elsewhere.

**Comment by vtrxxl** [comment]
> I am not stupid, but listing ruzzian forums on here is too much.

Seems like you are

**Comment by mhaeuser** [comment]
I will not bother going into why this narrative is completely deranged, it is obvious enough. Further spam will yield an organization-wide ban.

**Comment by kov-serg** [comment]
[YarosMallorca](https://github.com/YarosMallorca) you and people like you fan the flames of war. You may be now are not able to understand that the state and people are completely different entities. And there are enough bastards in any country. You shouldn’t become like a brainless herd.

**Pull request closed without merging**
